### PR TITLE
trackers: fix building with gcc

### PR DESCRIPTION
**Pull request by pierrecdn**
Without including inttypes.h, compilation of 2.2 fails with such errors:
```
track_file.c:450:32: error: expected ')' before 'PRIi64'
```
Here was my build config:
```
Keepalived configuration
------------------------
Keepalived version       : 2.2.0
Compiler                 : gcc gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Preprocessor flags       : -D_GNU_SOURCE -I/usr/include/libnl3
Compiler flags           : -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wall -Wextra -Wunused -Wstrict-prototypes -Wabsolute-value -Waddress-of-packed-member -Walloca -Walloc-zero -Warray-bounds=2 -Wattribute-alias -Wbad-function-cast -Wcast-align -Wcast-qual -Wdate-time -Wdisabled-optimization -Wdouble-promotion -Wduplicated-branches -Wduplicated-cond -Wfloat-conversion -Wfloat-equal -Wformat-overflow -Wformat-security -Wformat-signedness -Wformat-truncation -Wframe-larger-than=5120 -Wimplicit-fallthrough=3 -Winit-self -Winline -Wjump-misses-init -Wlogical-op -Wmissing-declarations -Wmissing-field-initializers -Wmissing-prototypes -Wnested-externs -Wnormalized -Wnull-dereference -Wold-style-definition -Woverlength-strings -Wpointer-arith -Wredundant-decls -Wshadow -Wshift-overflow=2 -Wstack-protector -Wstrict-overflow=4 -Wstrict-prototypes -Wstringop-overflow=2 -Wsuggest-attribute=cold -Wsuggest-attribute=const -Wsuggest-attribute=format -Wsuggest-attribute=malloc -Wsuggest-attribute=noreturn -Wsuggest-attribute=pure -Wsync-nand -Wtrampolines -Wundef -Wuninitialized -Wunknown-pragmas -Wunsuffixed-float-constants -Wunused-const-variable=2 -Wunused-macros -Wvariadic-macros -Wwrite-strings -fPIE -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -O2
Linker flags             : -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -pie -Wl,-z,relro -Wl,-z,now
Extra Lib                : -lm -lcrypto -lssl -lnl-3 -lnl-genl-3 -lpcre2-8
Use IPVS Framework       : Yes
IPVS use libnl           : Yes
IPVS syncd attributes    : Yes
IPVS 64 bit stats        : Yes
HTTP_GET regex support   : Yes
fwmark socket support    : Yes
Use VRRP Framework       : No
Use BFD Framework        : No
SNMP vrrp support        : No
SNMP checker support     : No
SNMP RFCv2 support       : No
SNMP RFCv3 support       : No
DBUS support             : No
SHA1 support             : Yes
Use JSON output          : No
libnl version            : 3
Use IPv4 devconf         : No
Use iptables             : No
Use nftables             : No
systemd integration      : No
init type                : systemd
Strict config checks     : No
Build genhash            : Yes
Build documentation      : No
```

### CODE REVIEW

**Comment by pqarmitage** [comment]
@pierrecdn Many thanks for the patch.

I didn't get that error on the systems I use, so out of interest could you advise what distro/version you are using; it might be that we can add that to the systems we check builds on.

**Comment by pierrecdn** [comment]
@pqarmitage The distro for which we noticed this are CentOS 7 and 8. Both when using the standard gcc (4.8.5 on CentOS7) and gcc 9.3.

**Comment by pqarmitage** [comment]
It is clearly correct that track_file.c should include <inttypes.h>, but I don't get a compilation error on CentOS 8 if I don't specifically include it.

For me, track_file.c includes vrrp_scheduler.h at line 47, which includes vrrp.h at line 36, which includes <netinet/ip6.h> at line 36, and this includes <inttypes.h> at line 22.

Alternatively, if configure was run with the `--disable-vrrp` option track_file.c includes check_data.h at line 44 which includes <openssl/ssl.h> at line 34 which includes <openssl/e_os2.h> at line 15, which includes <openssl/opensslconf.h> at line 13, and that includes <inttypes.h> at line 224 subject to various conditions.

The only way that I can see that the error can occur is if VRRP is disabled, and either OPENSSL_SYS_UEFI is defined or
```
# elif (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || \
     defined(__osf__) || defined(__sgi) || defined(__hpux) || \
     defined(OPENSSL_SYS_VMS) || defined (__OpenBSD__)
```
is not true.

Since, on CentOS 8 __STDC_VERSION__ is 201710, the only option left is that OPENSSL_SYS_UEFI is defined, but I can't find anywhere that that is defined.

@pierrecdn Are you able to shed any light on this?

**Comment by pierrecdn** [comment]
I was wrong about CentOS 8, my CI is merging the logs for both builds, so I was wrong. Actually, only CentOS7 is failing.
Also, I confirm VRRP is disabled explicitely in our builds, using `--disable-vrrp`.

**Comment by pqarmitage** [comment]
On CentOS7 the openssl header files do not include <inttypes.h>, so at least that explains the problem (and I too get the compilation failure stating PRIi64 is not defined.

**Pull request merged**
