### PR TITLE
Docs: adding code of conduct documentation

### PR DESCRIPTION
**Pull request by johannbg**
This PR adds a COC. 
Added your ( Alexandre ) address as the contact for such incidents but perhaps Quentin might be preferred since he's more active in the community on groups.io

### CODE REVIEW

**Comment by pqarmitage** [comment]
While the ideas behind the Code of Conduct are highly laudable, I am not convinced that it works as it is worded.

For example, the opening paragraphs:

This code of conduct outlines our `who is our?` expectations for participants within the Keepalived community `what is the Keepalived community?`, as well as steps for reporting unacceptable behavior.
We are committed to providing a welcoming and inspiring community `in what sense does anyone provide the community?` for all and expect our code of conduct to be honored. 
Anyone who violates this code of conduct may be banned from the community `how is someone banned from the community? I am not aware that we can stop someone submitting an issue or a pull request for example`.

Some parts of it are just not possible:
```
## 1. Correction

**Community Impact**: Use of inappropriate language or other behavior deemed
unprofessional or unwelcome in the community.

**Consequence**: A private, written warning from community leaders, providing
clarity around the nature of the violation and an explanation of why the
behavior was inappropriate. A public apology may be requested.
```

Leaving aside that `deemed unprofessional or unwelcome in the community` is a matter of opinion and opinions may differ, if someone were to use inappropriate language in a Github issue report (and there have been times when the language as interpreted by a native English speaker was inappropriate, but the language was probably due to a non-native English speaker doing their best to write English), we have no means to provide `A private, written warning` since we often have no direct contact details (which presumably would have to be an email address) to contact an individual privately.

As I said, the ideas behind the Code of Conduct are highly laudable, but the above are just some examples of how I don't see that this specific Code of Conduct can work for a project like keepalived, or indeed any project hosted on the likes of Github.

**Comment by johannbg** [comment]
Well I'm not a native english speaker and our in that sense was meant as the representive of the entire keepalived community which is made of it's contributors and consumers as it is in other software projects. "Our pledge" and anything below it is the Contributor covenant used by many projects as can be seen here https://www.contributor-covenant.org/adopters/ 
 
Now most people in the software world know that this cant be effectively enforced. 
That said one of the reason that OSS projects implement this is lowering the barrier of entries in the projects ( having COC in place does help that for bad actors even if they are rare they do exist ) as well as to complete their community profile https://github.com/acassen/keepalived/community ( which is what I was aiming at doing with this and the security PR ), which in turn are efforts to increases the likelyhood that this ends up on contributors radars since most projects want to increase contributors to it. 

Now if the keepalived project leaders consider having a COC is unhelpful for the project we can just close this PR.

**Comment by pqarmitage** [comment]
@johannb We have considered and discussed this pull request. 

We feel that it would be quite wrong and misleading to our users if we were to suggest that we were adopting this, or any similar, code of conduct by merging such a document.

To start with I raised the point above that the Enforcement Guidelines could not be adhered to, to which you replied:
> Now most people in the software world know that this cant be effectively enforced.

This means that we would be misrepresenting our intent right from the start of adopting the CoC. Quite frankly one of the key elements that I think is essential to a Code of Conduct is a expectation to be honest and truthful; if this CoC were to be adopted we would manifestly be failing in that from day one. This in turn would immediately make people realise that the adoption was merely an exercise in bureaucracy/political correctness, and not something of substance.

The document as presented appears to be very far from a Code of Conduct, but more a statement about equal opportunities and non-discrimination. I would expect the key points of a CoC to include honesty, integrity, behaving ethically and in accordance with the law. Given that this is a software project, I would also expect to see statements about not deliberately submitting malicious code, nor code that is subject to copyright, and that contributors will not seek to waste the time of other contributors/users. Nothing anywhere near approaching these is included in the proposed CoC.

Notwithstanding the above, the opening section that has been added, and is not in the Contributor Covenant Code of Conduct at https://www.contributor-covenant.org is misleading and ambiguous. What is the "Keepalived community"; I can think of many answers that people may suggest, but none of them is a community. Keepalived is a software project intended to provide a solution useful to as many people as possible; it is not our _intention_ to provide a community (whether welcoming, inspiring or otherwise), although one or more communities might arise depending on how people respond.

Moving on to the pledge, who are _members_ of the community? They are clearly distinct from contributors, and so are presumably users. Who is a user? Is it someone who installs, configures and runs keepalived; or is it someone who, unbeknownst to them, makes use of keepalived because they access a web server via a network that uses keepalived?

The document as proposed is so full of holes and ambiguities that I would suggest that anyone who adopted it, especially for an open source software project, had not actually considered it properly, and that therefore the adoption was at best meaningless, and at worst misleading.

We are very distressed to have been subjected to an attempt to put us in a position of mislead our users, albeit I have no reason to believe that it was not done with the best of intentions, and ask that before you submit further requests you fully consider their implications.

**Comment by acassen** [comment]
Our code of conduct and mainly mindset is : NO CODE OF CONDUCT ! just trust the source (luke) and hard work ! everything else is overhead... in other words freedom

**Pull request closed without merging**
