### PR TITLE
Issue: #484 Set vrrp script default value to 2 as defined by the documentation in…

### PR DESCRIPTION
**Pull request by joncastro**
… keepalived.conf.SYNOPSIS

### CODE REVIEW

**Comment by pqarmitage** [comment]
I think the difficulty with this approach is that it is changing the default behaviour of keepalived, and so this patch could break some existing configurations.

Probably what should be done is the documentation should be updated to match the way keepalived currently works. Also doc/man/man5/keepalived.conf.5 needs to be changed to keep it in step with keepalived.SYNOPSIS.

**Comment by joncastro** [comment]
Thanks @pqarmitage  for your comment.

I agree that changing the documentation might be a valid solution in most cases but in this particular case keeping `weight` as default value `0` does not seem the right approach because defining track script with `weight` `0` does not influence in the priority and consequently it is like not defining the track script.

The user would expect that if a track script is defined it will influence the priority in order to keep MASTER the one that contains the most stable state of the system.

For example, if we have a two nodes running a webserver like `nginx` and a track script like:
```
vrrp_script chk_nginx {
       script "killall -0 nginx"
       interval 1
}
vrrp_instance VI_1 {
        ...
        track_script {
          chk_nginx
        }
        ...
}
```

then the user would expect that by default the master node will contain the node that runs nginx, but if `weight` is defined to `0` then the track script has not influence and MASTER node will be any node independently if nginx is running or not.

If existing deployment contains a configuration with no `weight` it will fix the issue keeping MASTER node the one that contains highest priority based on defined track scripts, aligning the deployment with the documentation and expected behavior.

Finally, I think setting `weight` to `0` does not seems valid in most cases and if the user really wants setting `weight` to `0` then this value should be manually provided via `weight 0` configuration line instead of being the default keepalived behavior.

**Comment by pqarmitage** [comment]
Please see the last 2 paragraphs of section 2 of keepalived.SYNOPSIS (which contradicts what is stated at 2.1). A weight of 0 (which is the same as not specifying the weight) is a special case (since as you say it would otherwise do nothing itself), and it causes the vrrp instance to go to fault state if the script returns a non-zero exit code (the same also applies for track_interface).

I certainly have configurations that use this feature, and I have no doubt that others do too.

**Comment by joncastro** [comment]
In that case, I agree. It would be better to update the documentation. I will close the pull request.

**Pull request closed without merging**
