### PR TITLE
add sctp and persistence engine support

### PR DESCRIPTION
**Pull request by vrit**

### CODE REVIEW

**Comment by acassen** [comment]
Hello,

it seems last merge broke your pull request. would you submit it again ?

**Comment by vrit** [comment]
Now it should be ok.

**Comment by acassen** [comment]
607b398 is going to generate issue if I proceed to pull request merge. I must close your pull request. Please submit a new one after.

Regs,
Alexandre

**Comment by vrit** [comment]
ok, no problem.

BR,
Riccardo

**Pull request closed without merging**
