### PR TITLE
Add a proper license file

### PR DESCRIPTION
**Pull request by johannbg**
Since this is somewhat out of norm having to do for a repo and there seem to be keepalived forks under different license on github best to clarify this stuff hence this pull request but I have to ask. 

Is this your own personal account and this is fork of keepalived with upstream being hosted somewhere else or is this the upstream keepalived repository?  ( the repo also lacks typical release and test stuff for upstream project ) 

If this is upstream why did you chose to have it under your personal account but not under it's own project account on github ( sorry was going to ask on the ~mailinglist~ but had to do some weird steps and create account on a site called groups.io which needed approval to be able to join the discussion forum for the project ).

### CODE REVIEW

**Comment by acassen** [comment]
This is the upstream main repo. I did it, well, hmm, something like in 2010 so I never changed. Release as tarball are on Keepalived website, test tools are mostly personal stuff. Quentin exposed some of his testing tools. License is already present in keepalived document root from the very first release back in 2000.

**Comment by johannbg** [comment]
@acassen  Providing a proper licence files in the format LICENSE, LICENSE.txt or LICENSE.md in repositories on github is the prefered way to go these days ( along with providing # SPDX-License-Identifier: headers into files where applicable ). The reason for doing so is for consistency and correctness for the automatic licensing tools parsing ( github ) repositories, which kinda end up being inaccurate if people are stuffing this into all kinds of weirdly named files. 

I will be submitting pull requests for other "grooming" tasks in the repo ( from quick look the rpm spec file is outdated, the contribution file not being autogenerate by git commits etc. ) if you dont mind. 

There are also seems also be lacking coding style when submitting patches along with contribution documentation. 

Then there is the question if the repo should not be Coverity scanned, using oss-fuzz and LGTM  for security scans etc. 

And I probably should make a mkosi pull reqest on @pqarmitage fork of this repo so you have something tangible to test and try while going through mkosi upstream documentation + you probably should/want to get familiar with casync and varlink the ipc protocol as well in the process to see if that's something useful for the project.

**Comment by acassen** [comment]
well, it seems GitHub is supporting COPYING file too. I am going to revert previous merge because as explained in GPL legal stuff from FSF, COPYING file is the convention.

**Comment by acassen** [comment]
https://github.com/licensee/licensee/blob/dc079ede1a71b593a1b29f9ffa55017f1464148c/lib/licensee/project_files/license_file.rb#L24

**Comment by johannbg** [comment]
No mention of it here...
https://help.github.com/en/articles/licensing-a-repository

**Comment by johannbg** [comment]
To be more specific how their own tools work

"Detecting a license
The open source Ruby gem Licensee compares the repository's LICENSE file to a short list of known licenses. Licensee also provides the Licenses API and gives us insight into how repositories on GitHub are licensed"....

**Pull request merged**
