### PR TITLE
add advert_count option

### PR DESCRIPTION
**Pull request by xiezhenye**
add advert_count option to configure how many vrrp advertisement will cause role switch instead of hard coded 3

### CODE REVIEW

**Comment by DStape** [comment]
I agree that the 3 does seem arbitrary, however this is the value stated in the RFC (https://tools.ietf.org/html/rfc5798) for the master down interval:

Advertisement interval contained in ADVERTISEMENTS received from the Master (centiseconds).  This value is saved by virtual routers in the Backup state and used to compute Skew_Time and Master_Down_Interval.  The initial value is the same as Advertisement_Interval.

**Comment by xiezhenye** [comment]
3 can be the default value to match the RFC, but is too sensitive for some cases.

**Comment by acassen** [comment]
please modify pull request to make it default to 3 to match RFC.

**Comment by DStape** [comment]
In the cases that it is too sensitive then you should bump up the vrrp advertisement interval. Based on the RFC, I don't feel that this value should be configurable. However, 3 multiplies the advertisement interval anyway, so there is already a means to adjust this value.

**Pull request closed without merging**
